on:
  push:
    branches: [main]

defaults:
      run:
        working-directory: dna-mutant-detector

jobs:
  coverage-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Run Tests + JaCoCo
        run: mvn clean verify
      - name: Upload JaCoCo HTML
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-report
          path: dna-mutant-detector/target/site/jacoco
  coverage-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests + Jest
        run: npm run test:coverage
      - name: Upload Jest Coverage
        uses: actions/upload-artifact@v6
        with:
          name: jest-coverage
          path: dna-mutant-detector-front/coverage/lcov 